
services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: HotelSite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2005vino2024
    ports:
    - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  backend:
    build:
      context: ./HotelSiteBackend  # Set the context to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5001:8000"  # Backend слушает порт 8000 внутри контейнера
    depends_on:
      - db
    image: kireyd/backend:latest
    environment:
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=HotelSite
      - DB_USER=postgres
      - DB_PASSWORD=2005vino2024

    
  frontend:
    build:
      context: ./hotel-project
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ""  # Frontend будет делать запросы к /api, nginx проксирует на backend
    ports:
      - "3000:80"  # Nginx слушает порт 80 внутри контейнера
    depends_on:
      - backend
    image: kireyd/frontend:latest

volumes:
  postgres_data: