name: Deploy to VPS via SSH

on:
  push:
    branches: ["dev"]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: add ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name:  Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: 🚀 Deploy to VPS
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "
            set -e
            echo 'Change directory to project'
            cd /home/HotelSiteTailwind || exit 1

            echo 'Stop previous conteiners'
            docker-compose down

            echo 'Rebuild new vresion'
            docker-compose up --build -d

            echo 'Ready'
          "
